[2018-06-24 22:33:23,744][Thread-1:6548][task_id:django.request][base.py:93][WARNING][Not Found: /]
[2018-06-24 22:33:23,823][Thread-3:6972][task_id:django.request][base.py:93][WARNING][Not Found: /favicon.ico]
[2018-06-24 22:33:39,969][Thread-5:6052][task_id:django.request][exception.py:118][ERROR][Internal Server Error: /test_template/]
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\x\IdeaProjects\test_template\app01\views.py", line 31, in test_template
    'script':script
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 454, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 663, in __init__
    self.args_check(filter_name, filter_func, args)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 723, in args_check
    (name, alen - dlen, plen))
django.template.exceptions.TemplateSyntaxError: default requires 2 arguments, 1 provided
[2018-06-24 22:45:41,740][Thread-3:3008][task_id:django.request][exception.py:118][ERROR][Internal Server Error: /test_template/]
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\x\IdeaProjects\test_template\app01\views.py", line 31, in test_template
    'script':script
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 454, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 663, in __init__
    self.args_check(filter_name, filter_func, args)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 723, in args_check
    (name, alen - dlen, plen))
django.template.exceptions.TemplateSyntaxError: truncatechars requires 2 arguments, 1 provided
[2018-06-24 23:03:52,266][Thread-1:3320][task_id:django.request][exception.py:118][ERROR][Internal Server Error: /test_template/]
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\x\IdeaProjects\test_template\app01\views.py", line 31, in test_template
    'script':script
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 454, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 663, in __init__
    self.args_check(filter_name, filter_func, args)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 723, in args_check
    (name, alen - dlen, plen))
django.template.exceptions.TemplateSyntaxError: add_str requires 2 arguments, 1 provided
[2018-06-24 23:11:16,423][Thread-1:4672][task_id:django.request][exception.py:118][ERROR][Internal Server Error: /test_template/]
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\x\IdeaProjects\test_template\app01\views.py", line 31, in test_template
    'script':script
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 454, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '% if forloop.first %' from '% if forloop.first %'
[2018-06-24 23:14:13,211][Thread-3:5176][task_id:django.request][exception.py:118][ERROR][Internal Server Error: /test_template/]
Traceback (most recent call last):
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\x\IdeaProjects\test_template\app01\views.py", line 31, in test_template
    'script':script
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 815, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 454, in parse
    raise self.error(token, e)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 452, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 568, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 668, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '% else %' from '% else %'
